name: Build flake packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: sokol-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: List packages
        id: packages
        run: |
          FLAKE_PACKAGES=$(nix flake show --json | jq -r '.packages["x86_64-linux"] | keys | map(".#\(.)") | .[]')
          echo $FLAKE_PACKAGES
          echo "FLAKE_PACKAGES<<EOF
          $FLAKE_PACKAGES
          EOF" >> "$GITHUB_ENV"

      - name: Build packages
        run: echo $FLAKE_PACKAGES | xargs nix build
