name: Build flake packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: List packages
        id: packages
        run: |
          FLAKE_PACKAGES=$(nix flake show --json | jq -r '.packages["x86_64-linux"] | keys | map(".#\(.)") | .[]')
          echo "LIST='$FLAKE_PACKAGES'" >> $GITHUB_OUTPUT

      - name: Build packages
        run: echo "${{ steps.vars.outputs.packages.LIST }}" | xargs nix build
